### ISSUE TITLE
Add microformats

### ISSUE THREAD

**Issue by growdigital** [growdigital/groundwork#5]
By adding microformatting, will have better search results and previews on RSS feed

**Comment by growdigital** [comment]
Lots of reference:
https://moz.com/blog/meta-data-templates-123
http://ogp.me/
https://blog.bufferapp.com/twitter-cards-guide
https://cards-dev.twitter.com/validator
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html
http://schema.org/Article

**Comment by gRegorLove** [comment]
Will this also include http://microformats.org/wiki/h-entry?

**Comment by growdigital** [comment]
It will now 👍 . I'll have a look at it tonight 🙂

**Comment by growdigital** [comment]
h-entry finishing touch, thank you @gRegorLove 
052592834aaf3ab5f6a038b763626fc4bb8c7853
